n1 = int(input('Digite um valor: '))
n2 = int(input('Digite outro valor: '))
print('A soma vale {}.'.format(n1+n2), end= ' ')
print('A subtraçaõ vale {}.'.format(n1-n2), end= ' ')
print('A divusão é {:.3f}.'.format(n1/n2),end= ' ')
print('A multiplicação é {}.'.format(n2*n2), end = ' ')
